version: '3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: rentx-postgres
    environment:
      - POSTGRES_USER=rentx
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=rentx
    ports:
      - 5432:5432
    volumes:
      - $HOME/dataset/rentx/postgres:/var/lib/postgresql/data
    networks:
      - database-net

  backend:
    build: .
    container_name: rentx-api
    ports:
      - 3333:3333
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    networks:
      - database-net

networks:
  database-net:
    driver: bridge
